### ISSUE TITLE
Support the github.dev (use as VSCode Web Extension) ?

### ISSUE THREAD

**Issue by towry** [hogashi/vscode-copy-github-permalink#14]
It would be great for this plugin to support https://github.dev/.

**Comment by hogashi** [comment]
Oh I see. Should it be configured in extension setting (like `{ "permalink_host": "github.dev" }` ), or do you have any other ideas?

**Comment by towry** [comment]
Sorry for not specific, actually I mean [VsCode Web Extension](https://code.visualstudio.com/api/extension-guides/web-extensions). But with "github.dev" host support will be great too.

**Comment by hogashi** [comment]
@towry Unfortunately, it seems not to be possible for now. VSCode Web (github.dev) doesn't have `vscode.git` extension which is builtin to native app (on Node runtime). https://github.com/microsoft/vscode/issues/138550#issuecomment-988585654

I've found that you can use `GitHub issues: Copy GitHub Permalink` command alternatively. https://github.com/microsoft/vscode/issues/138550#issuecomment-988232342
It is provided with https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github which is preinstalled into VSCode Web (but it copies URL with hostname `github.dev` not `github.com` on github.dev ...)

Therefore, my extension seems to be able to be replaced with `GitHub.vscode-pull-request-github` extension in some usecases. So feel free to use any extensions as you like! (Of cource I'm happy if you use mine but you don't mind what you choose 🍵 )
